trigger:
- master

pool:
  vmImage: ubuntu-latest
stages:
- stage: SwaDEV
  displayName: SWA DEV

  jobs:
  - deployment: dev_deploy
    #pool:
    #  vmImage: $(vmImageName) 
    displayName: Deploy en Dev
    environment: 'DEV'
    variables:
      - name: environment
        value: DEV
      - group: ${{ format('variables-{0}', variables.environment) }}  
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureStaticWebApp@0
            inputs:
             app_location: '/'
             api_location: 'api'
      #  routes_location: '/public'
             azure_static_web_apps_api_token: $(swa_deployment_token)
        
- stage: qa_deploy
  jobs:
  - deployment: qa_deploy  #not a job... a deployment!
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'qa-hello'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "hello, qa world !!!"
            displayName: 'Msg Deploy QA'
